#!/bin/bash

cd
python start.py $1
cd /Users/edit/path/to/match/your/own/$1
git init
git remote add origin https://github.com/github username here/$1.git
touch README.md
git add .
git commit -m "first commit"
git push -u origin master
sublime .
