#!/bin/bash

cd
python start.py $1
cd /Users/malcolmherbert/Documents/Charlie/Projects/MyProjects/$1
git init
git remote add origin https://github.com/charmockridge/$1.git
touch README.md
git add .
git commit -m "first commit"
git push -u origin master
sublime .
