#!/bin/bash

cd
python start.py $1
cd /Users/malcolmherbert/Documents/Charlie/Projects/MyProjects/$1
git init
git add README.md
git commit -m "first commit"
git remote add origin https://github.com/charmockridge/$1.git
git push -u origin master
